This is a little bash script for browsing cheatsheets with fzf.

* Usage
** Browse
   Just type the keyword and look at the preview.
** Add
   Hit =<C-l>= and you will go into the editor page.
   
   You can add more than one entry at a time, but you must start at the second line and the four lines are a group, which are the program(command), argument(keybinding), description and notes in order.
** Edit
*** Edit one entry
	Hit =<C-o>= and you will go into the editor page to edit current entry. The entry would be split into four lines.
	
	The old entry would be backed up at HISTORY_FILE( Default: =$HOME/.cache/cheet_histfile= ).
*** Edit all entries
	Hit =<C-p>= and you will go into the editor page. You will directly edit the cheatsheet file here.
** Format
   Hit =<C-r>= to format entries.
   If the lines begins with DELIMITER then they will be sorted, the other lines will be put at the last of sheet.
* Todo
  - Add argument =--editor= to specify the editor.

* Credits
  - fzf: https://github.com/junegunn/fzf
  - org-mode: https://orgmode.org/ (This tool is inspired by Org-mode)
  - Cheatsheets
	- org-mode: https://orgmode.org/worg/orgcard.html
	- tmux: https://gist.github.com/MohamedAlaa/2961058
